### ISSUE TITLE
能分享一下 Yelp, Amazon Books的logs文件吗

### ISSUE THREAD

**Issue by XUPT-guoruihan** [BELIEVEfxy/LightSANs#2]
您好！非常感谢您分享的代码 我注意到您的代码是运行在伯乐0.11版本上运行的   目前我在伯乐1.0版本和最新下载的ml-1m数据集上运行出来的结果与您论文中的结果有些偏差     请问您方便分享一下在Yelp, Amazon Books数据集上运行的logs文件吗？期待您的回复！

**Comment by BELIEVEfxy** [comment]
已更新

**Comment by XUPT-guoruihan** [comment]
收到 非常感谢您的回复 祝工作顺利
